export const AUTHORS = [
  "Elias Thorne",
  "Sienna Moreno",
  "Dr. Aris Vance",
  "Mira Kalu",
  "Julian Sterling",
  "Lydia Thorne",
  "Marcus Webb",
  "Elena Rossi",
  "Oliver Quinn",
  "Sophia Chen",
  "Nikos Papadakis",
  "Clara Whitby",
  "Jasper Finn",
  "Alistair Cook",
  "Zoe Henderson",
  "Felix Grant",
  "Ingrid Berg",
  "Hassan Al-Said",
  "Leona Rivers",
  "Arthur P. Dorman",
];
